// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80UTVqXVcg9eWCe0BkGw8RC9yfUtIAns',
    appId: '1:225507123974:web:08a0f8082b41310d7c7487',
    messagingSenderId: '225507123974',
    projectId: 'baroproject',
    authDomain: 'baroproject.firebaseapp.com',
    storageBucket: 'baroproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkfTPNO4vkXu59mB7cm6vLLIXFBGBEeoc',
    appId: '1:225507123974:android:c3ac5cd8cf63ddcc7c7487',
    messagingSenderId: '225507123974',
    projectId: 'baroproject',
    storageBucket: 'baroproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3_ohLpptlvRBtAtdXFEdWCp-rCdVcbI',
    appId: '1:225507123974:ios:97721563f4aa84417c7487',
    messagingSenderId: '225507123974',
    projectId: 'baroproject',
    storageBucket: 'baroproject.appspot.com',
    androidClientId: '225507123974-6ug0reqt7d44fume96ultglufuc3f0cq.apps.googleusercontent.com',
    iosClientId: '225507123974-96qt2r8o6rvevq4jkuead3eqdrtue6ni.apps.googleusercontent.com',
    iosBundleId: 'com.quadcore.baroProject',
  );
}
